/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tubes_tiket;

import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Lenovo
 */
public class arsip_pelanggan extends javax.swing.JFrame {
    public java.sql.Statement st;
    public ResultSet rs;
    public String sql;
    
    int baris = 0;
    static Object kolom[] = {"ID", "No Tiket", "Email Pemesan", "Jenis Wahana", "Tipe Tiket",
        "Diskon", "Total Harga", "Tanggal Pemesanan", "Status Tiket"};
    DefaultTableModel model = new DefaultTableModel(kolom, baris);

    public arsip_pelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_arsip = new javax.swing.JTable();
        btn_x = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 1200));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 228, 228));
        jPanel1.setMinimumSize(new java.awt.Dimension(2000, 1200));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_arsip.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tabel_arsip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "No Tiket", "Email Pemesan", "Jenis Wahana", "Tipe Tiket", "Diskon", "Total Harga", "Tanggal", "Status Tiket"
            }
        ));
        tabel_arsip.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabel_arsip.setMinimumSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setViewportView(tabel_arsip);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 1810, 600));

        btn_x.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_x.setText("X");
        btn_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xActionPerformed(evt);
            }
        });
        jPanel1.add(btn_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 50, 50, 30));

        jLabel1.setFont(new java.awt.Font("Garamond", 0, 36)); // NOI18N
        jLabel1.setText("ARSIP PELANGGAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 2350, 1180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
        try{
            Connection c=koneksi.getkoneksi();
            
            sql = "SELECT * FROM arsip";
            
            st= c.createStatement();
            rs= st.executeQuery(sql);
            
            model.getDataVector().removeAllElements();
            tabel_arsip.setModel(model);
            
            while (rs.next()){
                Object[] data={
                rs.getInt("id_arsip"),
                rs.getString("id_pesanan"),
                rs.getString("email_cust"),
                rs.getString("wahana"),
                rs.getString("jenis_tiket"),
                rs.getString("diskon"),
                rs.getFloat("total_harga"),
                rs.getString("tanggal_pemesanan"),
                rs.getString("status_tiket")
                };
                model.addRow(data);
            }
            
             tabel_arsip.getColumnModel().getColumn(0).setPreferredWidth(100); // Kolom ID
             tabel_arsip.getColumnModel().getColumn(1).setPreferredWidth(100); // Kolom No Tiket
             tabel_arsip.getColumnModel().getColumn(2).setPreferredWidth(250); // Kolom Email Pemesan
             tabel_arsip.getColumnModel().getColumn(3).setPreferredWidth(250); // Kolom Jenis Wahana
             tabel_arsip.getColumnModel().getColumn(4).setPreferredWidth(250); // Kolom Tipe Tiket
             tabel_arsip.getColumnModel().getColumn(5).setPreferredWidth(100); // Kolom Diskon
             tabel_arsip.getColumnModel().getColumn(6).setPreferredWidth(250); // Kolom Total Harga
             tabel_arsip.getColumnModel().getColumn(7).setPreferredWidth(300); // Kolom Tanggal
             tabel_arsip.getColumnModel().getColumn(8).setPreferredWidth(300); // Kolom Status Tiket
                
             tabel_arsip.setRowHeight(60);
                
             tabel_arsip.getTableHeader().setFont(new Font("Times New Roman", Font.PLAIN, 24));
                
                 
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formComponentShown

    private void btn_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xActionPerformed
        // TODO add your handling code here:
        new TUBES_LOGIN().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_xActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(arsip_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(arsip_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(arsip_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(arsip_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_x;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_arsip;
    // End of variables declaration//GEN-END:variables
}
