/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tubes_tiket;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;

/**
 *
 * @author Asus Rog flow
 */
public class Datatiket extends javax.swing.JFrame {

    public java.sql.Statement st;
    public ResultSet rs;
    public String sql, email;
    
    int baris = 0;
    static Object kolom[] = {"ID Pemesanan", "Jenis Wahana", "Tipe Tiket",
       "Tanggal Pemesanan"};
    DefaultTableModel model = new DefaultTableModel(kolom, baris);
    /**
     * Creates new form DataMahasiswa
     */
    public Datatiket(String Email) {
        initComponents();
        
        email = Email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_tiket = new javax.swing.JTable();
        btn_guna = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_x = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 1200));
        setPreferredSize(new java.awt.Dimension(2000, 1200));
        setSize(new java.awt.Dimension(2000, 1200));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_tiket.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        tabel_tiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_tiket.setIntercellSpacing(new java.awt.Dimension(4, 4));
        tabel_tiket.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabel_tiketAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabel_tiket.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabel_tiketComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_tiket);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 1580, 510));

        btn_guna.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        btn_guna.setText("Gunakan");
        btn_guna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gunaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guna, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 850, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1880, 1070));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Data Tiket Anda");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        btn_x.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_x.setText("X");
        btn_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xActionPerformed(evt);
            }
        });
        jPanel2.add(btn_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1880, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your   handling code here:
        
        try{
            Connection c=koneksi.getkoneksi();
            
            sql = "SELECT * FROM pesanan WHERE customer_emailcust = '" + email +"';";
            
            st= c.createStatement();
            rs= st.executeQuery(sql);
            
            model.getDataVector().removeAllElements();
            tabel_tiket.setModel(model);
            
            while (rs.next()){
                Object[] data={
                    rs.getInt("id_pesanan"),
                    rs.getString("wahana_nama_wahana"),
                    rs.getString("jenis_tiket"),
                    rs.getString("tanggal_pemesanan")
                };
                model.addRow(data);
            }
            
                tabel_tiket.getColumnModel().getColumn(0).setPreferredWidth(200); // Kolom ID Pemesanan
                tabel_tiket.getColumnModel().getColumn(1).setPreferredWidth(200); // Kolom Jenis Wahana
                tabel_tiket.getColumnModel().getColumn(2).setPreferredWidth(200); // Kolom Tipe Tiket
                tabel_tiket.getColumnModel().getColumn(3).setPreferredWidth(200); // Kolom Tanggal Pemesanan
                
                tabel_tiket.setRowHeight(60);
                
                 tabel_tiket.getTableHeader().setFont(new Font("Times New Roman", Font.PLAIN, 36));

            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void tabel_tiketComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabel_tiketComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_tiketComponentShown
    private void btn_gunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gunaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabel_tiket.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih tiket terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int idPesanan = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());

        Connection c = koneksi.getkoneksi();

        try {
            String updateArsip = "UPDATE arsip SET status_tiket = 'Digunakan' WHERE id_pesanan = " + idPesanan+";";
            String deletePesanan = "DELETE FROM pesanan WHERE id_pesanan = " + idPesanan+";";

            st.executeUpdate(updateArsip);
            st.executeUpdate(deletePesanan);

            model.removeRow(selectedRow);

            JOptionPane.showMessageDialog(this, "Tiket berhasil digunakan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menghapus tiket: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_gunaActionPerformed

    private void tabel_tiketAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabel_tiketAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_tiketAncestorAdded

    private void btn_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_xActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guna;
    private javax.swing.JButton btn_x;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_tiket;
    // End of variables declaration//GEN-END:variables
}
