/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tubes_tiket;

/**
 *
 * @author LENOVO
 */

import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


public class INVOICE_TUBES_2 extends javax.swing.JFrame {

    /**
     * Creates new form INVOICE_TUBES
     */
    
    public java.sql.Statement st;
    public ResultSet rs;
    public int Harga, idOrder;
    public String sql, Total, Nama, Email, Wahana, Tanggal, Tiket;
    public float uang_pembayaran, kembalian, nominal_pembayaran, Disk_val, nom_pajak;
    
    public INVOICE_TUBES_2(String nama, String email, String wahana, int harga, float disk_val, float total_pembayaran, String tanggal, String tiket, float Pajak) {
        initComponents();
        
        id_pelanggan.setText(email);
        nama_pelanggan.setText(nama);
        id_wahana.setText(wahana + " - " + String.valueOf(harga));
        Diskon.setText(String.valueOf(disk_val));
        jenis_tiket.setText(tiket);
        total_harga.setText("Rp. " + String.valueOf(total_pembayaran));
        pajak.setText("10%");
        tanggal_tiket.setText(tanggal);
        
        this.Wahana=wahana;
        this.Disk_val = disk_val;
        this.Harga=harga;
        this.Tanggal=tanggal;
        this.Tiket=tiket;
        this.Nama = nama;
        this.Email = email;
        this.nominal_pembayaran = total_pembayaran;
        this.nom_pajak = Pajak;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nominal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bayar = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Diskon = new javax.swing.JLabel();
        total_harga = new javax.swing.JLabel();
        id_pelanggan = new javax.swing.JLabel();
        jenis_tiket = new javax.swing.JLabel();
        id_wahana = new javax.swing.JLabel();
        tanggal_tiket = new javax.swing.JLabel();
        pajak = new javax.swing.JLabel();
        nama_pelanggan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(2000, 1200));
        setSize(new java.awt.Dimension(2000, 1200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel3.setText("Email Pelanggan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel4.setText("Wahana");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel6.setText("Jenis Tiket");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel7.setText("Tanggal Tiket");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel8.setText("Pajak");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel9.setText("Diskon");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel11.setText("Masukkan nominal ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 780, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 115));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel1.setText("INVOICE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1810, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2790, 90));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel13.setText(":");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel15.setText(":");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 20, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel16.setText(":");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 20, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel17.setText(":");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel18.setText(":");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel19.setText(":");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 780, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel5.setText("Nama ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel14.setText(":");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        nominal.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        getContentPane().add(nominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 780, 210, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel20.setText("Total Harga");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 690, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel21.setText(":");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 690, 20, -1));

        bayar.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        bayar.setText("Bayar");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 780, -1, 40));

        kembali.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 780, -1, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Diskon.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(Diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 320, 40));

        total_harga.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(total_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 280, 60));

        id_pelanggan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(id_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 280, 40));

        jenis_tiket.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(jenis_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 660, 40));

        id_wahana.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(id_wahana, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 420, 40));

        tanggal_tiket.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(tanggal_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 460, 40));

        pajak.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(pajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 380, 40));

        nama_pelanggan.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(nama_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 530, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1870, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
        
        uang_pembayaran = Float.parseFloat(nominal.getText());
        
        if (uang_pembayaran < nominal_pembayaran){
            JOptionPane.showMessageDialog(this, "Nominal Yang Dimasukkan Kurang");
        }else {
            try {
                kembalian = uang_pembayaran - nominal_pembayaran;
                JOptionPane.showMessageDialog(this, "Pembayaran Berhasil Dilakukan"+"\nKembalian Anda: "+kembalian);
                
                Connection c = koneksi.getkoneksi();
                st = c.createStatement();
                sql = "INSERT INTO pesanan (customer_emailcust, wahana_nama_wahana, jenis_tiket, diskon, total, tanggal_pemesanan) "+
                        "VALUES ('"+Email+"', '"+Wahana+"', '"+Tiket+"', '"
                        +Disk_val+"', "+nominal_pembayaran+", '"+Tanggal+"');";
                
                int rs = st.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
                
            if (rs > 0) {
                ResultSet generatedKeys = st.getGeneratedKeys();
                if (generatedKeys.next()) {
                    idOrder = generatedKeys.getInt(1); // Mendapatkan nilai idorder
                    JOptionPane.showMessageDialog(this, "ID Order Anda: " + idOrder);
                }
            }
            
             int pilih = JOptionPane.showConfirmDialog(this, "Apakah Anda ingin mencetak invoice?", "Cetak Invoice", JOptionPane.YES_NO_OPTION);
            
            if (pilih == JOptionPane.YES_OPTION) {
                cetakInvoice();
            }
            
                new Tiket(idOrder).setVisible(true);
                dispose();
                
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
           
        }
        
    }//GEN-LAST:event_bayarActionPerformed

private void cetakInvoice() {
    PrinterJob printerJob = PrinterJob.getPrinterJob();
    printerJob.setPrintable((graphics, pageFormat, pageIndex) -> {
        if (pageIndex > 0) {
            return Printable.NO_SUCH_PAGE;
        }

        Graphics2D g2d = (Graphics2D) graphics;
        g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

        String title = "STRUK PEMBAYARAN\n";
        String garis = "==============================\n";
        String customer = "Email Customer : " + Email + "\n";
        String wahana = "Nama Wahana    : " + Wahana + "\n";
        String tiket = "Jenis Tiket    : " + Tiket + "\n";
        String diskon = "Diskon         : " + Disk_val + "\n";
        String pajakText = "Pajak (10%)    : Rp " + String.valueOf(nom_pajak);
        String total = "Total Bayar    : Rp " + String.valueOf(nominal_pembayaran);
        String pembayaran = "Nominal Bayar  : Rp " + String.valueOf(uang_pembayaran);
        String kembalianText = "Kembalian      : Rp " + String.valueOf(kembalian);
        String terimaKasih = "\nTerima Kasih atas Kunjungan Anda!\n";

        g2d.setFont(new Font("Monospaced", Font.PLAIN, 14));
        int y = 20;
        int lineHeight = 15;

        g2d.drawString(title, 10, y);
        y += lineHeight;
        g2d.drawString(garis, 10, y);
        y += lineHeight;
        g2d.drawString(customer, 10, y);
        y += lineHeight;
        g2d.drawString(wahana, 10, y);
        y += lineHeight;
        g2d.drawString(tiket, 10, y);
        y += lineHeight;
        g2d.drawString(diskon, 10, y);
        y += lineHeight;
        g2d.drawString(total, 10, y);
        y += lineHeight;
        g2d.drawString(pembayaran, 10, y);
        y += lineHeight;
        g2d.drawString(pajakText, 10, y);
        y += lineHeight;
        g2d.drawString(kembalianText, 10, y);
        y += lineHeight;
        g2d.drawString(garis, 10, y);
        y += lineHeight;
        g2d.drawString(terimaKasih, 10, y);

        return Printable.PAGE_EXISTS;
    });

    if (printerJob.printDialog()) {
        try {
            printerJob.print();
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(this, "Gagal mencetak: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}

    
    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new Pemasanan_Tiket(Nama, Email).setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INVOICE_TUBES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INVOICE_TUBES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INVOICE_TUBES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INVOICE_TUBES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Diskon;
    private javax.swing.JButton bayar;
    private javax.swing.JLabel id_pelanggan;
    private javax.swing.JLabel id_wahana;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jenis_tiket;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel nama_pelanggan;
    private javax.swing.JTextField nominal;
    private javax.swing.JLabel pajak;
    private javax.swing.JLabel tanggal_tiket;
    private javax.swing.JLabel total_harga;
    // End of variables declaration//GEN-END:variables
}
