/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tubes_tiket;

/**
 *
 * @author Lenovo
 */

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

public class Tiket extends javax.swing.JFrame {

    public java.sql.Statement st;
    public ResultSet rs, rsupdate, rsdelete;
    public int nomor, idPesanan;
    public String sql, Email, Wahana, Tanggal;
    
    
    public Tiket(int id) {
        initComponents();
        idPesanan = id;
        
        try{
            Connection c=koneksi.getkoneksi();
            sql = "SELECT * FROM arsip WHERE id_pesanan = " + id;
            st= c.createStatement();
            rs= st.executeQuery(sql);
            
             if (rs.next()) {
                id_invoice.setText(String.valueOf(rs.getInt("id_pesanan")));
                nama.setText(rs.getString("email_cust"));
                jenis_tiket.setText(rs.getString("jenis_tiket"));
                jenis_wahana.setText(rs.getString("wahana"));
                tanggal_tiket.setText(rs.getString("tanggal_pemesanan"));
                no_tiket.setText(String.valueOf(rs.getInt("id_arsip")));
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan untuk ID Order: " + id, "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch (Exception e){
             JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengambil data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        no_tiket = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        nama = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        id_invoice = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        tanggal_tiket = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jenis_tiket = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jenis_wahana = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_x = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_guna = new javax.swing.JButton();
        cetak_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(2000, 1200));
        setSize(new java.awt.Dimension(2000, 1200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel4.setText("No. Tiket        :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 206, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel6.setText("Email             :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 215, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel7.setText("Jenis Tiket      :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel8.setText("Jenis Wahana  :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel9.setText("ID Invoice     :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 180, 194, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel10.setText("Tanggal Tiket :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 260, -1, -1));

        no_tiket.setColumns(20);
        no_tiket.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        no_tiket.setRows(5);
        jScrollPane1.setViewportView(no_tiket);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 177, 310, 50));

        nama.setColumns(20);
        nama.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        nama.setRows(5);
        jScrollPane2.setViewportView(nama);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 310, 60));

        id_invoice.setColumns(20);
        id_invoice.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        id_invoice.setRows(5);
        jScrollPane5.setViewportView(id_invoice);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 180, 302, 50));

        tanggal_tiket.setColumns(20);
        tanggal_tiket.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tanggal_tiket.setRows(5);
        jScrollPane6.setViewportView(tanggal_tiket);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 248, 300, 60));

        jenis_tiket.setColumns(20);
        jenis_tiket.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jenis_tiket.setRows(5);
        jScrollPane3.setViewportView(jenis_tiket);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 310, 60));

        jenis_wahana.setColumns(20);
        jenis_wahana.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jenis_wahana.setRows(5);
        jScrollPane4.setViewportView(jenis_wahana);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 320, 50));

        jLabel11.setFont(new java.awt.Font("Garamond", 1, 48)); // NOI18N
        jLabel11.setText("TIKET");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 273, -1, -1));

        btn_x.setText("X");
        btn_x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xActionPerformed(evt);
            }
        });
        getContentPane().add(btn_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(1824, 16, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 157, 121));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 150, 1930, 370));

        jPanel3.setBackground(new java.awt.Color(239, 207, 165));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_guna.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        btn_guna.setText("Gunakan");
        btn_guna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gunaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_guna, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 140, -1, -1));

        cetak_btn.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        cetak_btn.setText("Cetak");
        cetak_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetak_btnActionPerformed(evt);
            }
        });
        jPanel3.add(cetak_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 140, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 490, 1920, 470));

        jPanel1.setBackground(new java.awt.Color(239, 207, 165));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 1940, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xActionPerformed
        // TODO add your handling code here:
        dispose();
        new TUBES_LOGIN().setVisible(true);
    }//GEN-LAST:event_btn_xActionPerformed

    private void btn_gunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gunaActionPerformed
        // TODO add your handling code here:

        try {
            Connection c = koneksi.getkoneksi();
            st = c.createStatement();

            String updateArsip = "UPDATE arsip SET status_tiket = 'Digunakan' WHERE id_pesanan = " + idPesanan+";";
            st.executeUpdate(updateArsip);

            
            String deletePesanan = "DELETE FROM pesanan WHERE id_pesanan = "+idPesanan+";";
            st.executeUpdate(deletePesanan);

            JOptionPane.showMessageDialog(this, "Tiket berhasil digunakan dan data pesanan telah dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new TUBES_LOGIN().setVisible(true);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_gunaActionPerformed

    private void cetak_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak_btnActionPerformed
        // TODO add your handling code here:
        try {
            btn_guna.setVisible(false);
            cetak_btn.setVisible(false);
            btn_x.setVisible(false);

            BufferedImage image = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = image.createGraphics();
            paint(g2d);

            javax.swing.JFileChooser lokasifile = new javax.swing.JFileChooser();
            lokasifile.setDialogTitle("Pilih Lokasi untuk Menyimpan Tiket");
            lokasifile.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Gambar PNG", "png"));

            int pilhanuser = lokasifile.showSaveDialog(this);

            if (pilhanuser == javax.swing.JFileChooser.APPROVE_OPTION) {
                File file = lokasifile.getSelectedFile();

                if (!file.getName().toLowerCase().endsWith(".png")) {
                    file = new File(file.getAbsolutePath() + ".png");
                }

                ImageIO.write(image, "png", file);
                JOptionPane.showMessageDialog(this, "Tangkapan layar berhasil disimpan sebagai gambar PNG: " + file.getAbsolutePath(), "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            
        try {
            Connection c = koneksi.getkoneksi();
            st = c.createStatement();

            String updateArsip = "UPDATE arsip SET status_tiket = 'Dicetak' WHERE id_pesanan = " + idPesanan+";";
            st.executeUpdate(updateArsip);

            String deletePesanan = "DELETE FROM pesanan WHERE id_pesanan = "+idPesanan+";";
            st.executeUpdate(deletePesanan);
            
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

            btn_guna.setVisible(true);
            cetak_btn.setVisible(true);
            btn_x.setVisible(true);
            
            new TUBES_LOGIN().setVisible(true);
            dispose();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencetak: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cetak_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran_tiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guna;
    private javax.swing.JButton btn_x;
    private javax.swing.JButton cetak_btn;
    private javax.swing.JTextArea id_invoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jenis_tiket;
    private javax.swing.JTextArea jenis_wahana;
    private javax.swing.JTextArea nama;
    private javax.swing.JTextArea no_tiket;
    private javax.swing.JTextArea tanggal_tiket;
    // End of variables declaration//GEN-END:variables
}
